### ISSUE TITLE
Doesn't work out of the box, getting some HTTP 500 errors

### ISSUE THREAD

**Issue by corneliusroemer** [pixelbyaj/vsc_xsd#1]
Installed the extension but can't get it to work

**Comment by pixelbyaj** [comment]
Can you share me the screenshot please ?

**Comment by hasirci** [comment]
I have same results
![image](https://github.com/pixelbyaj/vsc_xsd/assets/70998636/a0becc93-6097-4068-b268-1aade8088263)

**Comment by pixelbyaj** [comment]
I think there might be issue with XSD. Is it possible for you to share me the one ?
Error trace show: **Type 'urn:rsrNamespace:XmlVersion_Type' is not declared.**

**Comment by hasirci** [comment]
Sure, I'm trying to create this form [sdscom-xml.zip](https://github.com/pixelbyaj/vsc_xsd/files/14341089/sdscom-xml.zip)

**Comment by pixelbyaj** [comment]
@hasirci declaration of the base type **eSDScom:BaseExposureControlPersonalProtection** is missing.

'Undefined complexType 'http://www.esdscom.eu/eSDScom:BaseExposureControlPersonalProtection' is used as a base for complex type extension.'

```
<xs:complexContent>
			<xs:extension base="eSDScom:BaseExposureControlPersonalProtection"> </xs:extension>
</xs:complexContent>
```
I have to close this issue as it is the XSD issue.
