### ISSUE TITLE
Unclear naming

### ISSUE THREAD

**Issue by r-dufour** [pixelbyaj/vsc_xsd#2]
This converter converts XSD to JSON Schema. JSON Schema is not the same as a JSON object

**Comment by pixelbyaj** [comment]
> This converter converts XSD to JSON Schema. JSON Schema is not the same as a JSON object

Can you please elaborate?

**Comment by pixelbyaj** [comment]
Closing this issue as it has no proper example to support the issue.

**Comment by pixelbyaj** [comment]
Closing this issue as it has no proper example to support the issue.
