### ISSUE TITLE
minInclusive and maxInclusive

### ISSUE THREAD

**Issue by r-dufour** [pixelbyaj/vsc_xsd#3]
minInclusive and maxInclusive are not being set properly when XSD is converted to JSON Schema

![image](https://github.com/user-attachments/assets/b5e41a8e-83ce-4383-a05b-8275f4e5d977)

![image](https://github.com/user-attachments/assets/417a6abf-7223-43eb-b5ee-9d0601ee93b2)

![image](https://github.com/user-attachments/assets/e8fd65cb-20b5-47e5-b01b-b11d1f46ada4)

**Comment by pixelbyaj** [comment]
Can you share me the XSD if possible?

**Comment by pixelbyaj** [comment]
new version released to resolve this issue
